[[Openresty]]
arch = "x86_64"
git-tree-sha1 = "f37d51ca03ed5219e0f448cd194fb94aa8b4f9f2"
libc = "musl"
os = "linux"

    [[Openresty.download]]
    sha256 = "e3a8144fcbf18c91646b6d6e552df0270adc0ad152973c5936172294d075fc68"
    url = "https://github.com/JuliaBinaryWrappers/Openresty_jll.jl/releases/download/Openresty-v1.21.4+0/Openresty.v1.21.4.x86_64-linux-musl.tar.gz"
[[Openresty]]
arch = "x86_64"
git-tree-sha1 = "39a96a63d32c35fc2ffde10cc4e1953759ff1a6e"
libc = "glibc"
os = "linux"

    [[Openresty.download]]
    sha256 = "a7d004f691d981990faf30184ec2b6121c1fc01a200897574248508ec8678d6d"
    url = "https://github.com/JuliaComputing/Openresty_jll.jl/releases/download/Openresty-v1.21.4+1/Openresty.v1.21.4.x86_64-linux-gnu.tar.gz"
